version: "3.8"
services:
  mongodb:
    image: mongo:8.0.11
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${DB_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${DB_PASSWORD}"
      MONGO_INITDB_DATABASE: "${DB_NAME}"
    volumes:
      - ./mongodbdata:/data/db
    ports:
      - "${DB_PORT}:27017"